.\" -*- nroff -*-
.TH FALL-FROM-GRACE 8 "November 24, 2012"
.SH FALL-FROM-GRACE
fall-from-grace \- non-intrusive userspace process supervisor
.SH SYNOPSIS
.B fall-from-grace
.RI [ OPTIONS ]
.SH DESCRIPTION
See https://github.com/bjornedstrom/fall-from-grace for more info.
.SH AUTHOR
fall-from-grace was written by Bjorn Edstrom <be@bjrn.se>.
